const ADMIN_EMAILS=['katlearn.admin@gmail.com'];
const FIREBASE_CONFIG={apiKey:'AIzaSyCgMDdCP0R5fW3QjhYrd3Ab8AJH3xYGiz8',authDomain:'elp---katlearn.firebaseapp.com',projectId:'elp---katlearn',storageBucket:'elp---katlearn.firebasestorage.app',messagingSenderId:'344478447672',appId:'1:344478447672:web:4ed109a40303d0b41b0ecd',measurementId:'G-KTW11GD97T'};
let db,auth,user,fb={},classes=[],selectedClass=null,teacherAccess=false;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const isTeacher=()=>teacherAccess;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function showPage(id){$$('.page').forEach(x=>x.classList.remove('active-page'));$('#'+id)?.classList.add('active-page');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='dashboard')loadDashboard();if(id==='classes')loadClasses();if(id==='students')loadStudents();if(id==='packs')loadPacks();if(id==='progress')loadProgress();window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('.menu-toggle').onclick=()=>$('.sidebar').classList.toggle('open');
function openModal(id){$('#'+id).classList.add('show')}function closeModal(id){$('#'+id).classList.remove('show')}$$('.modal-close').forEach(b=>b.onclick=()=>closeModal(b.dataset.modal));
async function initFirebase(){const [{initializeApp,getApps},{getFirestore,collection,doc,getDoc,getDocs,addDoc,setDoc,updateDoc,deleteDoc,query,orderBy,where,limit}]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js')]);const {getAuth,onAuthStateChanged,GoogleAuthProvider,signInWithPopup,signOut}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js');const app=getApps().length?getApps()[0]:initializeApp(FIREBASE_CONFIG);db=getFirestore(app);auth=getAuth(app);fb={collection,doc,getDoc,getDocs,addDoc,setDoc,updateDoc,deleteDoc,query,orderBy,where,limit,GoogleAuthProvider,signInWithPopup,signOut};onAuthStateChanged(auth,async u=>{user=u;teacherAccess=false;if(u){const profile=await fb.getDoc(fb.doc(db,'users',u.uid)).catch(()=>null);const role=profile?.exists()?profile.data()?.role:null;teacherAccess=ADMIN_EMAILS.includes((u.email||'').toLowerCase())||role==='teacher';}renderAuth();if(u&&isTeacher()){document.body.classList.remove('locked');await loadDashboard()}else{document.body.classList.add('locked');showPage('dashboard')}})}
function renderAuth(){const name=user?.displayName||user?.email?.split('@')[0]||'Giáo viên';$('#accountName').textContent=user?name:'Chưa đăng nhập';$('#accountEmail').textContent=user?.email||'';$('#loginBtn').hidden=!!user;$('#logoutBtn').hidden=!user;$('.auth-message').textContent=user&&!isTeacher()?'Tài khoản này chưa được cấp quyền giáo viên. Hãy đăng ký/đăng nhập bằng tài khoản có vai trò giáo viên.':user?'Đã đăng nhập và có quyền quản lý.':'Đăng nhập bằng tài khoản giáo viên để tiếp tục.'}
$('#loginBtn').onclick=async()=>{try{const result=await fb.signInWithPopup(auth,new fb.GoogleAuthProvider());const profile=await fb.getDoc(fb.doc(db,'users',result.user.uid)).catch(()=>null);if(!ADMIN_EMAILS.includes((result.user.email||'').toLowerCase())&&profile?.data()?.role!=='teacher')toast('Tài khoản này chưa được cấp quyền giáo viên.')}catch(e){toast('Không thể đăng nhập: '+e.message)}};$('#logoutBtn').onclick=async()=>{await fb.signOut(auth)};
async function loadDashboard(){if(!isTeacher())return;const [cs,us,ps]=await Promise.all([fb.getDocs(fb.collection(db,'classes')),fb.getDocs(fb.collection(db,'users')),fb.getDocs(fb.collection(db,'publicPacks'))]);classes=cs.docs.map(d=>({id:d.id,...d.data()}));$('#metricClasses').textContent=classes.length;$('#metricStudents').textContent=us.size;$('#metricPacks').textContent=ps.size;const active=us.docs.filter(d=>Number(d.data().energy||0)>0).length;$('#metricActive').textContent=active;$('#recentClasses').innerHTML=classes.slice(0,5).map(c=>`<div class="class-item"><strong>${esc(c.name)}</strong><small>${esc(c.grade||'')} · ${Number(c.studentCount||0)} học sinh</small></div>`).join('')||'<div class="empty">Chưa có lớp nào. Tạo lớp đầu tiên nhé.</div>'}
async function loadClasses(){if(!isTeacher())return;const snap=await fb.getDocs(fb.query(fb.collection(db,'classes'),fb.orderBy('createdAt','desc'))).catch(()=>fb.getDocs(fb.collection(db,'classes')));classes=snap.docs.map(d=>({id:d.id,...d.data()}));$('#classTable').innerHTML=classes.map(c=>`<tr><td><strong>${esc(c.name)}</strong><br><small>${esc(c.description||'')}</small></td><td>${esc(c.grade||'—')}</td><td>${Number(c.studentCount||0)}</td><td><span class="status-pill">Đang hoạt động</span></td><td><div class="actions"><button class="teacher-btn secondary" data-select-class="${c.id}">Mở</button><button class="teacher-btn danger" data-delete-class="${c.id}">Xóa</button></div></td></tr>`).join('')||'<tr><td colspan="5"><div class="empty">Chưa có lớp.</div></td></tr>';$('[data-create-class]')?.addEventListener('click',()=>openModal('classModal'));$$('[data-select-class]').forEach(b=>b.onclick=()=>{selectedClass=classes.find(c=>c.id===b.dataset.selectClass);$('#selectedClassName').textContent=selectedClass?.name||'Chưa chọn lớp';showPage('students')});$$('[data-delete-class]').forEach(b=>b.onclick=()=>deleteClass(b.dataset.deleteClass))}
$('#classForm').onsubmit=async e=>{e.preventDefault();if(!isTeacher())return;const data={name:$('#className').value.trim(),grade:$('#classGrade').value.trim(),description:$('#classDescription').value.trim(),teacherUid:user.uid,teacherEmail:user.email,studentCount:0,createdAt:Date.now(),updatedAt:Date.now()};if(!data.name)return;try{await fb.addDoc(fb.collection(db,'classes'),data);closeModal('classModal');e.target.reset();toast('✓ Đã tạo lớp mới');loadClasses();loadDashboard()}catch(err){toast('Không thể tạo lớp: '+err.message)}};
async function deleteClass(id){if(!confirm('Xóa lớp này? Dữ liệu học sinh trong tài khoản vẫn được giữ nguyên.'))return;try{await fb.deleteDoc(fb.doc(db,'classes',id));if(selectedClass?.id===id)selectedClass=null;toast('Đã xóa lớp');loadClasses();loadDashboard()}catch(e){toast('Không thể xóa lớp: '+e.message)}}
async function getMembers(cls){const snap=await fb.getDocs(fb.collection(db,'classes',cls.id,'members'));return snap.docs.map(d=>({id:d.id,...d.data()}))}
async function loadStudents(){if(!isTeacher())return;$('#classSelector').innerHTML=classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(!selectedClass&&classes[0])selectedClass=classes[0];if(selectedClass){$('#classSelector').value=selectedClass.id;await renderStudents(selectedClass)}else $('#studentList').innerHTML='<div class="empty">Hãy tạo lớp trước.</div>'}
$('#classSelector').onchange=()=>{selectedClass=classes.find(c=>c.id===$('#classSelector').value);renderStudents(selectedClass)};
async function renderStudents(cls){if(!cls)return;$('#selectedClassName').textContent=cls.name;const members=await getMembers(cls);if(!members.length){$('#studentList').innerHTML='<div class="empty">Lớp chưa có học sinh. Bấm “Thêm học sinh”.</div>';return}const rows=await Promise.all(members.map(async m=>{try{const s=await fb.getDoc(fb.doc(db,'users',m.uid));return s.exists()?{id:s.id,...s.data(),member:m}:{...m}}catch{return m}}));$('#studentList').innerHTML=rows.map(s=>`<div class="student-row"><span class="student-avatar">${esc((s.displayName||s.email||'K')[0]).toUpperCase()}</span><div><strong>${esc(s.displayName||'KatLearn Student')}</strong><small>${esc(s.email||s.member?.email||'')}</small></div><div class="student-score"><b>⚡ ${Number(s.energy||0).toLocaleString()}</b><small>🪙 ${Number(s.coins||0).toLocaleString()} KatCoin</small></div><button class="teacher-btn danger" data-remove-student="${s.uid||s.member?.uid}">×</button></div>`).join('');$$('[data-remove-student]').forEach(b=>b.onclick=()=>removeStudent(cls,b.dataset.removeStudent))}
$('#studentForm').onsubmit=async e=>{e.preventDefault();if(!selectedClass)return toast('Chọn lớp trước.');const email=$('#studentEmail').value.trim().toLowerCase();if(!email)return;try{const q=fb.query(fb.collection(db,'users'),fb.where('email','==',email),fb.limit(1));const snap=await fb.getDocs(q);if(snap.empty)return toast('Không tìm thấy tài khoản học sinh với email này.');const d=snap.docs[0];await fb.setDoc(fb.doc(db,'classes',selectedClass.id,'members',d.id),{uid:d.id,email,addedAt:Date.now()});const count=(await getMembers(selectedClass)).length;await fb.updateDoc(fb.doc(db,'classes',selectedClass.id),{studentCount:count,updatedAt:Date.now()});closeModal('studentModal');e.target.reset();toast('✓ Đã thêm học sinh vào lớp');renderStudents(selectedClass);loadDashboard()}catch(err){toast('Không thể thêm học sinh: '+err.message)}};
async function removeStudent(cls,uid){try{await fb.deleteDoc(fb.doc(db,'classes',cls.id,'members',uid));const count=(await getMembers(cls)).length;await fb.updateDoc(fb.doc(db,'classes',cls.id),{studentCount:count,updatedAt:Date.now()});toast('Đã xóa học sinh khỏi lớp');renderStudents(cls);loadDashboard()}catch(e){toast('Không thể xóa học sinh: '+e.message)}}
async function loadPacks(){if(!isTeacher())return;const snap=await fb.getDocs(fb.collection(db,'publicPacks'));const packs=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||b.createdAt||0)-(a.createdAt?.seconds||a.createdAt||0));$('#packTable').innerHTML=packs.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${Array.isArray(p.words)?p.words.length:0}</td><td>${esc(p.createdBy||'')}</td><td><div class="actions"><button class="teacher-btn secondary" data-view-pack="${p.id}">Xem</button><button class="teacher-btn danger" data-delete-pack="${p.id}">Xóa</button></div></td></tr>`).join('')||'<tr><td colspan="4"><div class="empty">Chưa có bộ từ công khai.</div></td></tr>';$$('[data-delete-pack]').forEach(b=>b.onclick=()=>deletePack(b.dataset.deletePack));$$('[data-view-pack]').forEach(b=>b.onclick=()=>viewPack(packs.find(p=>p.id===b.dataset.viewPack)))}
function viewPack(p){if(!p)return;$('#packDetail').innerHTML=`<h3>${esc(p.name)}</h3><p>${Array.isArray(p.words)?p.words.length:0} từ vựng</p><div class="word-table-card"><div class="word-table-head"><span>Từ</span><span>Nghĩa</span><span>Phiên âm</span><span></span></div>${(p.words||[]).map(w=>`<div class="word-table-row"><span><b>${esc(w.word)}</b></span><span>${esc(w.mean)}</span><span>${esc(w.pron||'—')}</span><span>📚</span></div>`).join('')}</div>`;openModal('packModal')}
async function deletePack(id){if(!confirm('Xóa bộ từ công khai này?'))return;try{await fb.deleteDoc(fb.doc(db,'publicPacks',id));toast('Đã xóa pack');loadPacks();loadDashboard()}catch(e){toast('Không thể xóa pack: '+e.message)}}
$('#packForm').onsubmit=async e=>{e.preventDefault();const name=$('#packName').value.trim();const raw=$('#packWords').value.trim();try{const words=raw.split('\n').map(line=>{const [word,mean,pron]=line.split('|').map(x=>x.trim());return{word,mean,pron:pron||'',emoji:'📚'}}).filter(x=>x.word&&x.mean);if(!name||!words.length)return toast('Nhập tên pack và ít nhất một dòng Anh | Việt | IPA.');await fb.addDoc(fb.collection(db,'publicPacks'),{name,words,createdBy:user.uid,createdAt:Date.now(),updatedAt:Date.now()});closeModal('packCreateModal');e.target.reset();toast('✓ Đã xuất bản pack');loadPacks();loadDashboard()}catch(err){toast('Không thể tạo pack: '+err.message)}};
async function loadProgress(){if(!isTeacher())return;const members=selectedClass?await getMembers(selectedClass):[];if(!members.length){$('#progressTable').innerHTML='<div class="empty">Chọn một lớp có học sinh để xem tiến độ.</div>';return}const rows=await Promise.all(members.map(async m=>{const s=await fb.getDoc(fb.doc(db,'users',m.uid));return s.exists()?{id:s.id,...s.data()}:{...m}}));rows.sort((a,b)=>Number(b.energy||0)-Number(a.energy||0));$('#progressTable').innerHTML=rows.map((s,i)=>`<div class="student-row"><b>#${i+1}</b><span class="student-avatar">${esc((s.displayName||'K')[0]).toUpperCase()}</span><div><strong>${esc(s.displayName||'KatLearn Student')}</strong><small>${esc(s.email||'')}</small></div><div class="student-score"><b>⚡ ${Number(s.energy||0).toLocaleString()}</b><small>📚 ${Number(s.totalWords||0)} từ</small></div></div>`).join('')}
$('#addStudentBtn').onclick=()=>openModal('studentModal');$('#createPackBtn').onclick=()=>openModal('packCreateModal');$('#createClassBtn').onclick=()=>openModal('classModal');$('#viewProgressBtn').onclick=()=>showPage('progress');$('#goClasses').onclick=()=>showPage('classes');$('#goStudents').onclick=()=>showPage('students');$('#goPacks').onclick=()=>showPage('packs');$('#goProgress').onclick=()=>showPage('progress');
initFirebase().catch(e=>{console.error(e);toast('Firebase chưa sẵn sàng: '+e.message)});