const ADMIN_EMAILS=['katlearn.admin@gmail.com'];
const FIREBASE_CONFIG={apiKey:'AIzaSyCgMDdCP0R5fW3QjhYrd3Ab8AJH3xYGiz8',authDomain:'elp---katlearn.firebaseapp.com',projectId:'elp---katlearn',storageBucket:'elp---katlearn.firebasestorage.app',messagingSenderId:'344478447672',appId:'1:344478447672:web:4ed109a40303d0b41b0ecd',measurementId:'G-KTW11GD97T'};
const LMS_HOME='https://lms-katlearn.netlify.app';
const TEACHER_HOME='https://teacher-katlearn.vercel.app';
const SSO_EXCHANGE=TEACHER_HOME+'/api/auth-exchange';
let db,auth,user,fb={},classes=[],selectedClass=null,teacherAccess=false;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const isTeacher=()=>teacherAccess;
const isAdminUser=()=>ADMIN_EMAILS.includes((user?.email||'').toLowerCase());
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function showPage(id){$$('.page').forEach(x=>x.classList.remove('active-page'));$('#'+id)?.classList.add('active-page');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='dashboard')loadDashboard();if(id==='classes')loadClasses();if(id==='students')loadStudents();if(id==='packs')loadPacks();if(id==='progress')loadProgress();window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('.menu-toggle').onclick=()=>$('.sidebar').classList.toggle('open');
function openModal(id){$('#'+id).classList.add('show')}function closeModal(id){$('#'+id).classList.remove('show')}$$('.modal-close').forEach(b=>b.onclick=()=>closeModal(b.dataset.modal));

function clearSsoHash(){if(location.hash.includes('katlearn_id_token'))history.replaceState(null,document.title,location.pathname+location.search)}
function showBlocked(message='Bạn hiện là học sinh, chúng tôi xin phép khóa cổng để bạn không chạy lung tung'){
  document.body.classList.add('locked');
  const box=document.createElement('div');box.id='katlearnRoleLock';box.innerHTML=`<div class="kat-role-lock-card"><div class="kat-role-lock-icon">🚫</div><div class="kat-role-lock-error">ERROR!</div><h1>${esc(message)}</h1><p>Cổng giáo viên chỉ dành cho tài khoản giáo viên.</p><button id="katBackStudent">Quay về trang học sinh của bạn</button></div>`;
  const style=document.createElement('style');style.textContent='#katlearnRoleLock{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;background:linear-gradient(135deg,#fff7f8,#f7f5ff);padding:24px}.kat-role-lock-card{width:min(560px,100%);padding:42px 34px;text-align:center;background:#fff;border:1px solid #eee6f0;border-radius:28px;box-shadow:0 24px 80px #3c31501c}.kat-role-lock-icon{font-size:54px;margin-bottom:10px}.kat-role-lock-error{font:800 14px "Be Vietnam Pro",system-ui;color:#d94c68;letter-spacing:.12em}.kat-role-lock-card h1{margin:12px auto 8px;max-width:480px;font:700 24px/1.35 Fredoka,"Be Vietnam Pro",system-ui;color:#3e3549}.kat-role-lock-card p{color:#8b8295;font:500 13px/1.6 "Be Vietnam Pro",system-ui}.kat-role-lock-card button{margin-top:18px;border:0;border-radius:13px;padding:13px 20px;background:#f47c93;color:#fff;font:700 13px "Be Vietnam Pro",system-ui;cursor:pointer}.kat-role-lock-card button:hover{filter:brightness(.97);transform:translateY(-1px)}';document.head.appendChild(style);document.body.appendChild(box);$('#katBackStudent').onclick=()=>location.replace(LMS_HOME);}
async function exchangeSsoToken(idToken){
  const response=await fetch(SSO_EXCHANGE,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idToken})});
  const data=await response.json().catch(()=>({}));
  if(!response.ok){const err=new Error(data.error||'Không thể đồng bộ tài khoản');err.role=data.role;throw err}
  return data;
}
async function consumeIncomingSso(){
  const hash=new URLSearchParams(location.hash.replace(/^#/,'')||'');
  const token=hash.get('katlearn_id_token');
  if(!token)return false;
  clearSsoHash();
  try{
    const data=await exchangeSsoToken(token);
    if(data.role!=='teacher')throw Object.assign(new Error('STUDENT_ACCOUNT'),{role:'student'});
    sessionStorage.setItem('katlearn-teacher-access','1');
    const {signInWithCustomToken}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js');
    await signInWithCustomToken(auth,data.customToken);
    return true;
  }catch(e){
    if(e.role==='student'||e.message==='STUDENT_ACCOUNT'){showBlocked();return false}
    console.error('[KatLearn SSO]',e);
    return false;
  }
}
let ssoAttempted=sessionStorage.getItem('katlearn-sso-teacher-attempt')==='1';
async function startCrossAppCheck(){
  if(ssoAttempted||new URLSearchParams(location.search).has('sso'))return;
  ssoAttempted=true;sessionStorage.setItem('katlearn-sso-teacher-attempt','1');
  location.replace(LMS_HOME+'/sso-bridge.html?return=teacher');
}
async function initFirebase(){const [{initializeApp,getApps},{getFirestore,collection,doc,getDoc,getDocs,addDoc,setDoc,updateDoc,deleteDoc,query,orderBy,where,limit}]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js')]);const {getAuth,onAuthStateChanged,GoogleAuthProvider,signInWithPopup,signOut}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js');const app=getApps().length?getApps()[0]:initializeApp(FIREBASE_CONFIG);db=getFirestore(app);auth=getAuth(app);fb={collection,doc,getDoc,getDocs,addDoc,setDoc,updateDoc,deleteDoc,query,orderBy,where,limit,GoogleAuthProvider,signInWithPopup,signOut};onAuthStateChanged(auth,async u=>{user=u;teacherAccess=false;if(u){const cached=sessionStorage.getItem('katlearn-teacher-access')==='1';if(cached||ADMIN_EMAILS.includes((u.email||'').toLowerCase()))teacherAccess=true;else{const tokenResult=await u.getIdTokenResult().catch(()=>null);teacherAccess=tokenResult?.claims?.teacherAccess===true;if(!teacherAccess){const profile=await fb.getDoc(fb.doc(db,'users',u.uid)).catch(()=>null);const role=profile?.exists()?profile.data()?.role:null;teacherAccess=role==='teacher';}}}else sessionStorage.removeItem('katlearn-teacher-access');renderAuth();if(u&&isTeacher()){document.body.classList.remove('locked');await loadDashboard()}else{document.body.classList.add('locked');showPage('dashboard')}})}
function renderAuth(){const name=user?.displayName||user?.email?.split('@')[0]||'Giáo viên';$('#accountName').textContent=user?name:'Chưa đăng nhập';$('#accountEmail').textContent=user?.email||'';$('#loginBtn').hidden=!!user;$('#logoutBtn').hidden=!user;$('.auth-message').textContent=user&&!isTeacher()?'Tài khoản này chưa được cấp quyền giáo viên. Hãy đăng ký/đăng nhập bằng tài khoản có vai trò giáo viên.':user?'Đã đăng nhập và có quyền quản lý.':'Đăng nhập bằng tài khoản giáo viên để tiếp tục.'}
$('#loginBtn').onclick=async()=>{try{const result=await fb.signInWithPopup(auth,new fb.GoogleAuthProvider());const profile=await fb.getDoc(fb.doc(db,'users',result.user.uid)).catch(()=>null);if(!ADMIN_EMAILS.includes((result.user.email||'').toLowerCase())&&profile?.data()?.role!=='teacher')toast('Tài khoản này chưa được cấp quyền giáo viên.')}catch(e){toast('Không thể đăng nhập: '+e.message)}};$('#logoutBtn').onclick=async()=>{await fb.signOut(auth)};
async function loadDashboard(){if(!isTeacher())return;const [cs,us,ps]=await Promise.all([fb.getDocs(fb.collection(db,'classes')),fb.getDocs(fb.collection(db,'users')),fb.getDocs(fb.collection(db,'publicPacks'))]);classes=cs.docs.map(d=>({id:d.id,...d.data()})).filter(x=>isAdminUser()||x.teacherUid===user.uid);$('#metricClasses').textContent=classes.length;const students=us.docs.filter(d=>{const r=String(d.data().role||'student').toLowerCase();return r!=='teacher'&&r!=='admin'});$('#metricStudents').textContent=students.length;$('#metricPacks').textContent=ps.size;const active=students.filter(d=>Number(d.data().energy||0)>0).length;$('#metricActive').textContent=active;$('#recentClasses').innerHTML=classes.slice(0,5).map(c=>`<div class="class-item"><strong>${esc(c.name)}</strong><small>${esc(c.grade||'')} · ${Number(c.studentCount||0)} học sinh</small></div>`).join('')||'<div class="empty">Chưa có lớp nào. Tạo lớp đầu tiên nhé.</div>'}
async function loadClasses(){if(!isTeacher())return;const snap=await fb.getDocs(fb.query(fb.collection(db,'classes'),fb.orderBy('createdAt','desc'))).catch(()=>fb.getDocs(fb.collection(db,'classes')));classes=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>isAdminUser()||x.teacherUid===user.uid);$('#classTable').innerHTML=classes.map(c=>`<tr><td><strong>${esc(c.name)}</strong><br><small>${esc(c.description||'')}</small></td><td>${esc(c.grade||'—')}</td><td>${Number(c.studentCount||0)}</td><td><span class="status-pill">Đang hoạt động</span></td><td><div class="actions"><button class="teacher-btn secondary" data-select-class="${c.id}">Mở</button><button class="teacher-btn danger" data-delete-class="${c.id}">Xóa</button></div></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">Chưa có lớp.</div></td></tr>';$$('[data-select-class]').forEach(b=>b.onclick=()=>{selectedClass=classes.find(c=>c.id===b.dataset.selectClass);$('#selectedClassName').textContent=selectedClass?.name||'Chưa chọn lớp';showPage('students')});$('[data-delete-class]').forEach(b=>b.onclick=()=>deleteClass(b.dataset.deleteClass));const search=$('#classSearch');if(search)search.oninput=()=>{const q=search.value.trim().toLowerCase();$('#classTable tr').forEach(row=>row.style.display=!q||row.textContent.toLowerCase().includes(q)?'':'none')};}
$('#classForm').onsubmit=async e=>{e.preventDefault();if(!isTeacher())return;const data={name:$('#className').value.trim(),grade:$('#classGrade').value.trim(),description:$('#classDescription').value.trim(),teacherUid:user.uid,teacherEmail:user.email,studentCount:0,joinCode:makeJoinCode(),createdAt:Date.now(),updatedAt:Date.now()};if(!data.name)return;try{const classRef=await fb.addDoc(fb.collection(db,'classes'),data);await fb.setDoc(fb.doc(db,'classInvites',data.joinCode),{classId:classRef.id,className:data.name,teacherUid:user.uid,active:true,createdAt:Date.now(),updatedAt:Date.now()});closeModal('classModal');e.target.reset();toast('✓ Đã tạo lớp mới');loadClasses();loadDashboard()}catch(err){toast('Không thể tạo lớp: '+err.message)}};
async function deleteClass(id){if(!confirm('Xóa lớp này? Dữ liệu học sinh trong tài khoản vẫn được giữ nguyên.'))return;try{await fb.deleteDoc(fb.doc(db,'classes',id));if(selectedClass?.id===id)selectedClass=null;toast('Đã xóa lớp');loadClasses();loadDashboard()}catch(e){toast('Không thể xóa lớp: '+e.message)}}
async function getMembers(cls){const snap=await fb.getDocs(fb.collection(db,'classes',cls.id,'members'));return snap.docs.map(d=>({id:d.id,...d.data()}))}
async function loadStudents(){if(!isTeacher())return;$('#classSelector').innerHTML=classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');if(!selectedClass&&classes[0])selectedClass=classes[0];if(selectedClass){$('#classSelector').value=selectedClass.id;await renderStudents(selectedClass)}else $('#studentList').innerHTML='<div class="empty">Hãy tạo lớp trước.</div>'}
$('#classSelector').onchange=()=>{selectedClass=classes.find(c=>c.id===$('#classSelector').value);renderStudents(selectedClass)};$('#copyClassCodeBtn').onclick=()=>{if(!selectedClass)return toast('Chọn lớp trước.');copyText(selectedClass.joinCode||'Chưa có mã lớp')};
async function renderStudents(cls){if(!cls)return;$('#selectedClassName').textContent=cls.name;const members=await getMembers(cls);if(!members.length){$('#studentList').innerHTML='<div class="empty">Lớp chưa có học sinh. Bấm “Thêm học sinh”.</div>';return}const rows=await Promise.all(members.map(async m=>{try{const s=await fb.getDoc(fb.doc(db,'users',m.uid));return s.exists()?{id:s.id,...s.data(),member:m}:{...m}}catch{return m}}));$('#studentList').innerHTML=rows.map(s=>`<div class="student-row"><span class="student-avatar">${esc((s.displayName||s.email||'K')[0]).toUpperCase()}</span><div><strong>${esc(s.displayName||'KatLearn Student')}</strong><small>${esc(s.email||s.member?.email||'')}</small></div><div class="student-score"><b>⚡ ${Number(s.energy||0).toLocaleString()}</b><small>🪙 ${Number(s.coins||0).toLocaleString()} KatCoin</small></div><button class="teacher-btn danger" data-remove-student="${s.uid||s.member?.uid}">×</button></div>`).join('');$$('[data-remove-student]').forEach(b=>b.onclick=()=>removeStudent(cls,b.dataset.removeStudent))}
$('#studentForm').onsubmit=async e=>{e.preventDefault();if(!selectedClass)return toast('Chọn lớp trước.');const email=$('#studentEmail').value.trim().toLowerCase();if(!email)return;try{const q=fb.query(fb.collection(db,'users'),fb.where('email','==',email),fb.limit(1));const snap=await fb.getDocs(q);if(snap.empty)return toast('Không tìm thấy tài khoản học sinh với email này.');const d=snap.docs[0];await fb.setDoc(fb.doc(db,'classes',selectedClass.id,'members',d.id),{uid:d.id,email,addedAt:Date.now()});const count=(await getMembers(selectedClass)).length;await fb.updateDoc(fb.doc(db,'classes',selectedClass.id),{studentCount:count,updatedAt:Date.now()});closeModal('studentModal');e.target.reset();toast('✓ Đã thêm học sinh vào lớp');renderStudents(selectedClass);loadDashboard()}catch(err){toast('Không thể thêm học sinh: '+err.message)}};
async function removeStudent(cls,uid){try{await fb.deleteDoc(fb.doc(db,'classes',cls.id,'members',uid));const count=(await getMembers(cls)).length;await fb.updateDoc(fb.doc(db,'classes',cls.id),{studentCount:count,updatedAt:Date.now()});toast('Đã xóa học sinh khỏi lớp');renderStudents(cls);loadDashboard()}catch(e){toast('Không thể xóa học sinh: '+e.message)}}
async function loadPacks(){if(!isTeacher())return;const snap=await fb.getDocs(fb.collection(db,'publicPacks'));const packs=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||b.createdAt||0)-(a.createdAt?.seconds||a.createdAt||0));$('#packTable').innerHTML=packs.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${Array.isArray(p.words)?p.words.length:0}</td><td>${esc(p.createdBy||'')}</td><td><div class="actions"><button class="teacher-btn secondary" data-view-pack="${p.id}">Xem</button><button class="teacher-btn danger" data-delete-pack="${p.id}">Xóa</button></div></td></tr>`).join('')||'<tr><td colspan="4"><div class="empty">Chưa có bộ từ công khai.</div></td></tr>';$$('[data-delete-pack]').forEach(b=>b.onclick=()=>deletePack(b.dataset.deletePack));$$('[data-view-pack]').forEach(b=>b.onclick=()=>viewPack(packs.find(p=>p.id===b.dataset.viewPack)))}
function viewPack(p){if(!p)return;$('#packDetail').innerHTML=`<h3>${esc(p.name)}</h3><p>${Array.isArray(p.words)?p.words.length:0} từ vựng</p><div class="word-table-card"><div class="word-table-head"><span>Từ</span><span>Nghĩa</span><span>Phiên âm</span><span></span></div>${(p.words||[]).map(w=>`<div class="word-table-row"><span><b>${esc(w.word)}</b></span><span>${esc(w.mean)}</span><span>${esc(w.pron||'—')}</span><span>📚</span></div>`).join('')}</div>`;openModal('packModal')}
async function deletePack(id){if(!confirm('Xóa bộ từ công khai này?'))return;try{await fb.deleteDoc(fb.doc(db,'publicPacks',id));toast('Đã xóa pack');loadPacks();loadDashboard()}catch(e){toast('Không thể xóa pack: '+e.message)}}
async function loadPackChoices(){const select=$('#packSelect');if(!select||!db||!user)return;try{const snap=await fb.getDocs(fb.collection(db,'publicPacks'));const email=(user.email||'').toLowerCase();const packs=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>String(p.createdByUid||p.ownerUid||p.teacherUid||'')===String(user.uid)||String(p.createdBy||p.createdByEmail||p.ownerEmail||p.teacherEmail||'').toLowerCase()===email).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));select.innerHTML='<option value="">Chọn bộ từ của bạn...</option>'+packs.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name||'Bộ từ chưa đặt tên')+'</option>').join('');if(!packs.length)select.innerHTML='<option value="">Bạn chưa có bộ từ nào</option>';}catch(e){console.warn('Không tải được bộ từ của người dùng:',e);select.innerHTML='<option value="">Không tải được bộ từ</option>'}}
function refreshPackRowNumbers(){const rows=[...document.querySelectorAll('.pack-word-row')];rows.forEach((r,i)=>{const n=r.querySelector('.row-number');if(n)n.textContent='# '+(i+1)});const c=$('#packWordCount');if(c)c.textContent=rows.filter(r=>(r.querySelector('.pack-word')?.value||'').trim()&&(r.querySelector('.pack-mean')?.value||'').trim()).length}
function addPackRow(){const wrap=$('#packWordRows');if(!wrap)return;const row=document.createElement('div');row.className='pack-word-row';row.innerHTML='<span class="row-number"></span><input class="pack-word" placeholder="TỪ VỰNG" required><input class="pack-pron" placeholder="PHIÊN ÂM"><input class="pack-mean" placeholder="NGHĨA*" required><select class="pack-type"><option value="">LOẠI TỪ</option><option>noun</option><option>verb</option><option>adjective</option><option>adverb</option><option>phrase</option><option>other</option></select><input class="pack-example" placeholder="VÍ DỤ"><input class="pack-note" placeholder="GHI CHÚ"><button type="button" class="remove-pack-row" title="Xóa dòng">×</button>';wrap.appendChild(row);refreshPackRowNumbers();row.querySelector('.pack-word')?.focus()}
document.addEventListener('click',e=>{if(e.target.closest('#addPackRow')||e.target.closest('#quickAddBtn'))addPackRow();if(e.target.closest('.remove-pack-row')){const rows=document.querySelectorAll('.pack-word-row');if(rows.length>1)e.target.closest('.pack-word-row').remove();refreshPackRowNumbers()}if(e.target.closest('#cancelPackBtn'))closeModal('packCreateModal');if(e.target.closest('#newPackBtn')){const name=prompt('Tên bộ từ mới:');if(name?.trim())createNewPack(name.trim());}if(e.target.closest('.pack-help'))toast('Điền Từ vựng, Nghĩa và các thông tin bổ sung nếu cần.')});
document.addEventListener('input',e=>{if(e.target.closest('#packWordRows'))refreshPackRowNumbers()});
async function createNewPack(name){if(!isTeacher()||!user)return;try{const ref=await fb.addDoc(fb.collection(db,'publicPacks'),{name,words:[],createdBy:user.email||'',createdByUid:user.uid,createdAt:Date.now(),updatedAt:Date.now()});await loadPackChoices();$('#packSelect').value=ref.id;toast('✓ Đã tạo bộ từ mới')}catch(e){toast('Không thể tạo bộ từ: '+e.message)}}
$('#packForm').onsubmit=async e=>{e.preventDefault();const selectedId=$('#packSelect')?.value?.trim();const selectedOption=$('#packSelect option:checked');const name=selectedOption?.textContent?.trim()||'';const rows=[...document.querySelectorAll('.pack-word-row')];try{const words=rows.map(r=>({word:r.querySelector('.pack-word')?.value.trim(),pron:r.querySelector('.pack-pron')?.value.trim()||'',mean:r.querySelector('.pack-mean')?.value.trim(),type:r.querySelector('.pack-type')?.value||'',example:r.querySelector('.pack-example')?.value.trim()||'',note:r.querySelector('.pack-note')?.value.trim()||'',emoji:'📚'})).filter(x=>x.word&&x.mean);if(!selectedId)return toast('Hãy chọn một bộ từ của bạn.');if(!words.length)return toast('Nhập ít nhất một từ và nghĩa.');const ref=fb.doc(db,'publicPacks',selectedId);const existing=await fb.getDoc(ref);const oldWords=existing.exists()&&Array.isArray(existing.data()?.words)?existing.data().words:[];await fb.updateDoc(ref,{words:[...oldWords,...words],updatedAt:Date.now()});closeModal('packCreateModal');e.target.reset();$('#packWordRows').innerHTML='';addPackRow();toast('✓ Đã xuất bản pack');loadPacks();loadDashboard()}catch(err){toast('Không thể tạo pack: '+err.message)}};
async function loadProgress(){if(!isTeacher())return;const members=selectedClass?await getMembers(selectedClass):[];if(!members.length){$('#progressTable').innerHTML='<div class="empty">Chọn một lớp có học sinh để xem tiến độ.</div>';return}const rows=await Promise.all(members.map(async m=>{const s=await fb.getDoc(fb.doc(db,'users',m.uid));return s.exists()?{id:s.id,...s.data()}:{...m}}));rows.sort((a,b)=>Number(b.energy||0)-Number(a.energy||0));$('#progressTable').innerHTML=rows.map((s,i)=>`<div class="student-row"><b>#${i+1}</b><span class="student-avatar">${esc((s.displayName||'K')[0]).toUpperCase()}</span><div><strong>${esc(s.displayName||'KatLearn Student')}</strong><small>${esc(s.email||'')}</small></div><div class="student-score"><b>⚡ ${Number(s.energy||0).toLocaleString()}</b><small>📚 ${Number(s.totalWords||0)} từ</small></div></div>`).join('')}
$('#addStudentBtn').onclick=()=>openModal('studentModal');$('#createPackBtn').onclick=async()=>{await loadPackChoices();openModal('packCreateModal')};$('#createClassBtn').onclick=()=>openModal('classModal');$('#viewProgressBtn').onclick=()=>showPage('progress');$('#goClasses').onclick=()=>showPage('classes');$('#goStudents').onclick=()=>showPage('students');$('#goPacks').onclick=()=>showPage('packs');$('#goProgress').onclick=()=>showPage('progress');$('#goProgressCard').onclick=()=>showPage('progress');

function parseCsvLine(line){const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++;}else quoted=!quoted}else if(ch===','&&!quoted){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out}
async function importPackCsv(file){
  if(!file)return;
  try{
    const text=await file.text();
    const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
    if(!lines.length)throw new Error('File CSV trống.');
    const header=parseCsvLine(lines[0]).map(x=>x.toLowerCase());
    const find=(names,def)=>{const i=header.findIndex(h=>names.includes(h));return i>=0?i:def};
    const wi=find(['word','từ','từ vựng','english'],0), mi=find(['mean','meaning','nghĩa','vietnamese','tiếng việt'],2), pi=find(['pron','pronunciation','phiên âm'],1), ti=find(['type','loại từ'],3), ei=find(['example','ví dụ'],4), ni=find(['note','ghi chú'],5);
    const words=lines.slice(1).map(line=>{const a=parseCsvLine(line);return {word:a[wi]||'',pron:a[pi]||'',mean:a[mi]||'',type:a[ti]||'',example:a[ei]||'',note:a[ni]||'',emoji:'📚'}}).filter(w=>w.word&&w.mean);
    if(!words.length)throw new Error('Không tìm thấy dòng dữ liệu hợp lệ. CSV cần có ít nhất cột Từ vựng và Nghĩa.');
    const selectedId=$('#packSelect')?.value?.trim();
    if(!selectedId)throw new Error('Hãy chọn bộ từ trước khi nhập CSV.');
    const ref=fb.doc(db,'publicPacks',selectedId),snap=await fb.getDoc(ref),old=snap.exists()&&Array.isArray(snap.data()?.words)?snap.data().words:[];
    await fb.updateDoc(ref,{words:[...old,...words],updatedAt:Date.now()});
    toast('✓ Đã nhập '+words.length+' từ từ CSV');
    loadPacks();loadDashboard();$('#packFileInput').value='';
  }catch(e){toast('CSV: '+e.message)}
}
$('#importPackBtn').onclick=()=>{$('#packFileInput').click()};
$('#packFileInput').onchange=e=>importPackCsv(e.target.files?.[0]);

(async()=>{try{await initFirebase();const handled=await consumeIncomingSso();if(!handled&&!user&&!new URLSearchParams(location.search).has('sso'))await startCrossAppCheck();}catch(e){console.error(e);toast('Firebase chưa sẵn sàng: '+e.message)}})();
